#!/bin/sh
cd ~/webnxVite || exit 1;
fe_current_branch=$(git rev-parse --abbrev-ref HEAD);
fe_changes=$(git diff "origin/$fe_current_branch");
if [ $(wc "$fe_changes") -ne 0 ]; then
	# Pull newest changes from github
	git init;
	git pull;
	# Build front end
	npm install;
	npm run build;
	# Move built front end to static folder on backend
	mv ~/webnxVite/dist ~/webnxAPI/dist/static > /dev/null 2>&1
else
	echo "No changes on frontend, skipping build and copy"
fi
# Switch to backend folder
cd ~/webnxAPI || exit 1;
# Get current branch
be_current_branch=$(git rev-parse --abbrev-ref HEAD);
# Check for any changes
be_changes=$(git diff "origin/$fe_current_branch");
# If chnages were made on the backend
if [ $(wc "$be_changes") -ne 0 ]; then
	# Pull newest changes from github
	git init;
	git pull;
	# Build front end
	npm install;
	npm run build;
	# Clear pm2
	pm2 delete all;
	# Start new pm2 instances
	pm2 start dist/src/index.js --name webnxAPI -i 16;
else
	echo "No changes on backend, skipping build and restart"
fi
echo "Done."
# exit
exit 0;
